version: '3.9'
services:
  db-nest:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - networks_postsgres
networks:
  networks_postsgres:
